# Generated by Django 5.2.7 on 2025-11-17 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='recompensa',
            field=models.IntegerField(default=0),
        ),
    ]
