# Generated by Django 5.2.8 on 2025-11-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_actividad_recompensa'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividadasignada',
            name='evidencia_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actividadasignada',
            name='evidencia_texto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actividadasignada',
            name='fecha_entrega_real',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
