# Generated by Django 5.2.8 on 2025-11-19 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_add_saldo_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_user',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
