# Generated by Django 5.2.7 on 2025-11-03 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_alumno_delete_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='matricula',
            field=models.CharField(max_length=50),
        ),
    ]
