# Generated by Django 5.2.8 on 2025-11-19 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_add_saldo_field'),
    ]

    operations = [
    ]
